#server:
#  port: 443
#spring:
#  application:
#    name: optix

#eureka:
#  instance:
#    hostname: optux.herokuapp.com
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    service-url:
#      defaultZone: https://optux.herokuapp.com/eureka/
#  password: ${EUREKA_USER_PASSWORD:password}
server:
  port: ${$PORT:443}
security:
  user:
    password: ${eureka.password:password}

spring:
  application:
    name: eurekaserver

eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${server.port:80}/eureka/
  password: ${EUREKA_USER_PASSWORD:password}
 # server:
 #   waitTimeInMsWhenSyncEmpty: 0 https://calendar.google.com/calendar/u/0?cid=ZW1tYWNlZGlsbG9AaG90bWFpbC5jb20
