spring:
  application:
    name: optuxEureka

server:
  port: ${PORT:80}

security:
  user:
    password: ${eureka.password}

eureka:
  instance:
    hostname: optux.herokuapp.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: https://optux.herokuapp.com/eureka/
  password: ${EUREKA_USER_PASSWORD:password}

