#server:
#  port: 443
#spring:
#  application:
#    name: optix

#eureka:
#  instance:
#    hostname: optux.herokuapp.com
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    service-url:
#      defaultZone: https://optux.herokuapp.com/eureka/
#  password: ${EUREKA_USER_PASSWORD:password}

server:
  port: ${PORT:5000}
security:
  user:
    password: ${eureka.password}

spring:
  application:
    name: eurekaserver

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  password: ${EUREKA_USER_PASSWORD:password}
  server:
    waitTimeInMsWhenSyncEmpty: 0
